export interface UserConfiguration {
  /**
   * should auto switch this workspace to encrypted workspace
   */
  autoOpen?: boolean;

  /**
   * @default ["**\/*.md"]
   */
  include: string[];

  /**
   * @default ['.encrypt.json']
   */
  exclude: string[];

  /**
   * This is auto-generated by extension, please do not edit this property directly.
   * Other wise, it will cause the unknown problem.
   */
  extension: {
    include: string[];
    exclude: string[];
  };
}
